<div id="navigation">
	<div class="wrapper">
		<a href="<?php echo($baseURL) ?>">Home</a>
		<a href="<?php echo($baseURL."/develop/") ?>">Develop</a>
		<a href="<?php echo($baseURL."/design/") ?>">Design</a>
		<a href="<?php echo($baseURL."/draw/") ?>">Draw</a>
		<a href="<?php echo($baseURL."/about/") ?>">About</a>
		<a href="<?php echo($baseURL."/contact/") ?>">Contact</a>
		
		<a href="<?php echo($baseURL) ?>"><img src="<?php echo($baseURL."/img/jw.png") ?>" align="right" alt="JW" /></a>
	</div>
</div><!--end of navigation-->
