<a href="" data-largesrc="img/arrowsmith_card.png" data-title="Arrowsmith Baptist Church Business Card" data-description="Along with having refreshed the logo for <a href='http://www.arrowsmithchurch.com' target='_blank'>Arrowsmith Baptist Church</a> in Port Alberni, I designed business cards for all the staff. For the back of the cards (not pictured here) I had different features that would suit each person's needs (lines to write down an appointment, list of event times or a map to the building).">
							<img src="img/arrowsmith_card.png" height="250px" />
						</a>
