<a href="" data-largesrc="img/chapel.png" data-title="Chapel" data-description="Back in 2012, a few of my friends who were involved in a couple youth groups in South Vancouver started a monthly youth worship night called Chapel. I've been helping out at it since the beginning and while we started out small, we now have three locations in Greater Vancouver. As the techy one on the team I offered to make a website once we realized that what we had started was getting pretty big.<br /><br />
The website was started in 2013, but when you're dealing with something that is growing so fast, it's hard to keep up. We went through two different designs and requirements over about a year before we settled on what you see <a href='www.chapelvancouver.com' target='_blank'>here</a>. While building the site I made sure to make the website easily expandable as I know things will probably change a lot within another year. We have lots of new features planned as well, making the website a very iterative process.">
	 <img src="img/chapel.png" height="250px" />
</a>


