<a href="" data-largesrc="img/clixmag.png" data-title="Clixmag" data-description="While I was working at the <a href='http://www.rysa.bc.ca' target='_blank' >Richmond Youth Service Agency</a> in the summer of 2013, I was asked to create a new website for their youth-run blog, Clixmag. I decided to use Wordpress to develop the site as it would allow the youth to add their posts and manage the website themselves in my absence. While I was working on the website however I found that certain themes and plugins didn't do or look exactly as I wanted so I took to editing them. This required me to learn some PHP and Wordpress hooks but in the end I'm very pleased with the results and so are the youth!

<br /><br />You can view the site <a href='http://www.clixmag.ca' target='_blank' >here</a>.">
							<img src="img/clixmag.png" height="250px" />
						</a>
