<a href="" data-largesrc="img/doctor_who.png" data-title="Doctor Who" data-description="After a trip to Great Britain in 2012 I was convinced by my sister to start watching Doctor Who and boy was/am I hooked! It's become one of my favourite TV shows/franchises. I drew this portrait of Matt Smith as the 11th Doctor while I was watching through his first serial. Geronimo!">
	<img src="img/doctor_who.png" height="250px" />
</a>
