<a href="" data-largesrc="img/inspired.png" data-title="Inspired" data-description="As mentioned in the description of another one of my drawings, I'm a big fan of <a href='http://www.penny-arcade.com' target='_blank'>Penny Arcade</a>. Over the past few years I've been really inspired by the art style of their artist, Mike Krahulik. I drew this guy as a kind of merger between my style and his and was rather pleased with the result.">
							<img src="img/inspired.png" height="250px" />
						</a>
