<a href="" data-largesrc="img/ned.png" data-title="Nervous Ned" data-description="Nervous Ned is always nervous! Sometimes I'll just have a random thought pop into my head of something that I have to draw. This time it was &quotdraw a nervous guy&quot. His expression still makes me smile when I see it. I love that something that comes out of my head can then make that same head smile.">
							<img src="img/ned.png" height="250px" />
						</a>
