<a href="" data-largesrc="img/monster.png" data-title="Monster" data-description="I love this drawing. It started out as a real life cookie monster but ended up as something else that kind of resembles Sully from Monster's Inc. I never actually finished it, mainly out of fear of ruining it as I have trouble believing it came out of my hand. One day I'll build up enough courage and try to continue with it.">
							<img src="img/monster.png" height="250px" />
						</a>
