<a href="" data-largesrc="img/tobias.png" data-title="Tobias" data-description="If you're looking at this and thinking it's kind of weird you're thinking right. This is actually my first foray into drawing digitally. After purchasing a Wacom tablet and playing around with it a bit my cousin sent me a picture of himself and told me to draw it for him. I'm quite proud of the result, even if the subject matter is a little odd.">
							<img src="img/tobias.png" height="250px" />
						</a>
